## Python Module and Package

In [ ]:

from packageA.resource import pr
# import functions from a module

# import functions from a package



hi


## Function, Data types, Control Flow

In [90]:
# function
x = [3]
def add2(x):
  x[0] = x[0] +2

add2(x)
x

[5]

In [100]:
# conditional control flow
xx = 0
if False:
  xx = 3 

y = 4
print(xx,)

xxx = 0

i = 1
while  True:
  xxx = xxx + 2
  print(xxx)
  if i==2:   
    break
  i = i+1

xxx = 0
for i in [0, 1]:
  xxx = xxx +2
print(xxx)
# if 
# else

# Iterative Control flow
# while

# for


0
2
4
4


## Vector/matrix operations

In [64]:
import numpy as np

In [74]:
# define a vector
x = np.array([1, 2, 3, 4])
# print(x)
# print(x.shape)

# x.T
# x.transpose()
# transpose x
# print(x.T)

x == x.T

array([ True,  True,  True,  True])

In [77]:
# make vector to matrix
x.shape=(4, 1)
print(x)
x.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [70]:
# define a matrix
x = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4]])
x.shape

(2, 4)

In [79]:
# how about the following code?
x = np.array([1, 2, 3, 4])

# element-wise multipication:
# [1,2,3,4]
# [1,2,3,4]
1*1 + 2*2 + 3*3+4*4
print(x.dot(x))
print(x.dot(x.T))

30


In [85]:
# matrix multiplication

# define two matrices
A = np.random.randn(4,3)
print(np.shape(A))
print(A)
# print(A.dot(A)) # Error

C = np.random.randn(3,2)
# print(C)
# print(np.shape(C))
print(A.dot(C))
print(A.dot(C).shape)
# print('=======')
# print(np.dot(A,C))


(4, 3)
[[ 0.0760046  -0.5202442  -1.37636971]
 [-1.20088015  0.69273155  0.69123727]
 [-1.53258194 -0.15437113  0.29347153]
 [ 0.08414989  0.26526198  0.87011997]]
[[-0.57776892 -0.29970375]
 [ 1.29726448 -0.45476519]
 [ 0.05938168 -1.24829425]
 [ 0.22651155  0.24908685]]
(4, 2)


In [ ]:
# conformability


array([[1., 0.],
       [0., 1.]])

## Pass Activity

Define a string with a value equal to “Python is fun!”. Print every third character of this string.

Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.

Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.


In [109]:
#Define a string with a value equal to “Python is fun!”. Print every third character of this string.

string = "Python is fun!"
print(string[2::3])


# Create three list variables named 'StudentName', 'ID', and 'EmailAddress'. Add 5 random values in these lists and print them.
StudentName = np.random.randn(5)
ID = np.random.randn(5)
EmailAddress = np.random.randn(5)
print(StudentName, ID, EmailAddress )


# Create a dictionary variable with three keys, which are named same as the list created in the previous problem. Insert the previously created lists in the dictionary variable and print it.
d = {"StudentName":StudentName, "ID": ID,  "EmailAddress": EmailAddress}
print(d)

tnsu
[-0.56588678  0.22516407  0.75502785 -1.9739454   0.934994  ] [ 0.18195058 -1.31107589  1.09037749  0.29116634 -0.19000723] [ 0.0670728  -0.95254672  0.0260208  -0.19381965  0.6928877 ]
{'StudentName': array([-0.56588678,  0.22516407,  0.75502785, -1.9739454 ,  0.934994  ]), 'ID': array([ 0.18195058, -1.31107589,  1.09037749,  0.29116634, -0.19000723]), 'EmailAddress': array([ 0.0670728 , -0.95254672,  0.0260208 , -0.19381965,  0.6928877 ])}
